----------- INSERT ROLE DEFAULT
INSERT INTO DBO.APP_ROLE(APP_ROLE_NAME) VALUES('ROLE_ADMINISTRATOR');
INSERT INTO DBO.APP_ROLE(APP_ROLE_NAME) VALUES('ROLE_MEMBER');
INSERT INTO DBO.APP_ROLE(APP_ROLE_NAME) VALUES('ROLE_GUEST');

----------- INSERT USER DEFAULT
INSERT INTO DBO.APP_USER(APP_USER_NAME, ENCRYPTED_PASSWORD, CREATED_DATE, ENABLED, LOCKED) VALUES('APP_ADMINISTRATOR', '$2y$12$cHu12RgxejklJsCpQBTuQOqmAGnYYhP/av8pTzEtCYSzufz0YTW4u', GETDATE(), 'TRUE', 'FALSE');
INSERT INTO DBO.APP_USER(APP_USER_NAME, ENCRYPTED_PASSWORD, CREATED_DATE, ENABLED, LOCKED, LOCKED_DATE) VALUES('APP_MEMBER', '$2y$12$ymAq6pXOn3vXhQ9KPDLVW.dQpG5KYngU/Rr6Atmq6L9T8R1TDdbXe', GETDATE(), 'TRUE', 'TRUE', GETDATE());
INSERT INTO DBO.APP_USER(APP_USER_NAME, ENCRYPTED_PASSWORD, CREATED_DATE, ENABLED, LOCKED) VALUES('APP_GUEST', '$2y$12$JL3NG9l2IWSfL5dpwODKNupatk1ET3iQ2FgmOjw.C2Apxk3.8qGUa', GETDATE(), 'FALSE', 'FALSE');

----------- GRANT ROLE FOR USER
INSERT INTO DBO.APP_USER_ROLE(APP_USER_ID, APP_ROLE_ID) VALUES((SELECT AU.APP_USER_ID FROM APP_USER AU WHERE AU.APP_USER_NAME = 'APP_ADMINISTRATOR'), (SELECT AR.APP_ROLE_ID FROM APP_ROLE AR WHERE AR.APP_ROLE_NAME = 'ROLE_ADMINISTRATOR'));
INSERT INTO DBO.APP_USER_ROLE(APP_USER_ID, APP_ROLE_ID) VALUES((SELECT AU.APP_USER_ID FROM APP_USER AU WHERE AU.APP_USER_NAME = 'APP_MEMBER'), (SELECT AR.APP_ROLE_ID FROM APP_ROLE AR WHERE AR.APP_ROLE_NAME = 'ROLE_MEMBER'));
INSERT INTO DBO.APP_USER_ROLE(APP_USER_ID, APP_ROLE_ID) VALUES((SELECT AU.APP_USER_ID FROM APP_USER AU WHERE AU.APP_USER_NAME = 'APP_GUEST'), (SELECT AR.APP_ROLE_ID FROM APP_ROLE AR WHERE AR.APP_ROLE_NAME = 'ROLE_GUEST'));

----------- INSERT APP ACTION
INSERT INTO DBO.APP_ACTION(APP_ACTION_NAME) VALUES('CONFIRM_REGISTRATION');
INSERT INTO DBO.APP_ACTION(APP_ACTION_NAME) VALUES('UNLOCK_ACCOUNT');
INSERT INTO DBO.APP_ACTION(APP_ACTION_NAME) VALUES('FORGOT_PASSWORD');