----------- INSERT ROLE DEFAULT
INSERT INTO DBO.APP_ROLE(APP_ROLE_NAME) VALUES('ROLE_ADMINISTRATOR');
INSERT INTO DBO.APP_ROLE(APP_ROLE_NAME) VALUES('ROLE_MEMBER');
INSERT INTO DBO.APP_ROLE(APP_ROLE_NAME) VALUES('ROLE_GUEST');

----------- INSERT USER DEFAULT
INSERT INTO DBO.APP_USER(APP_USER_NAME, ENCRYPTED_PASSWORD, CREATED_DATE, ENABLED, LOCKED) VALUES('ADMINISTRATOR', '$2y$12$JPg3CKszIGdtB11agvZALus73WSo4lUpnSQzJd22Xjy.UrJYSr3Za', GETDATE(), 'TRUE', 'FALSE');
INSERT INTO DBO.APP_USER(APP_USER_NAME, ENCRYPTED_PASSWORD, CREATED_DATE, ENABLED, LOCKED) VALUES('APPMEMBER', '$2y$12$SdNv1Orft4PwXK0gkEp9tugK.wkUWx66JMDNr9SJ/ypb7K0lmC8XG', GETDATE(), 'TRUE', 'FALSE');
INSERT INTO DBO.APP_USER(APP_USER_NAME, ENCRYPTED_PASSWORD, CREATED_DATE, ENABLED, LOCKED) VALUES('APPGUEST', '$2y$12$g53ltYAQdADNvpiKUKP08emMfbH95r0NWHGvnjHOQKDGEGcmyZFza', GETDATE(), 'TRUE', 'FALSE');

----------- GRANT ROLE FOR USER
INSERT INTO DBO.APP_USER_ROLE(APP_USER_ID, APP_ROLE_ID) VALUES((SELECT AU.APP_USER_ID FROM APP_USER AU WHERE AU.APP_USER_NAME = 'ADMINISTRATOR'), (SELECT AR.APP_ROLE_ID FROM APP_ROLE AR WHERE AR.APP_ROLE_NAME = 'ROLE_ADMINISTRATOR'));
INSERT INTO DBO.APP_USER_ROLE(APP_USER_ID, APP_ROLE_ID) VALUES((SELECT AU.APP_USER_ID FROM APP_USER AU WHERE AU.APP_USER_NAME = 'APPMEMBER'), (SELECT AR.APP_ROLE_ID FROM APP_ROLE AR WHERE AR.APP_ROLE_NAME = 'ROLE_MEMBER'));
INSERT INTO DBO.APP_USER_ROLE(APP_USER_ID, APP_ROLE_ID) VALUES((SELECT AU.APP_USER_ID FROM APP_USER AU WHERE AU.APP_USER_NAME = 'APPGUEST'), (SELECT AR.APP_ROLE_ID FROM APP_ROLE AR WHERE AR.APP_ROLE_NAME = 'ROLE_GUEST'));

----------- INSERT APP ACTION
INSERT INTO DBO.APP_ACTION(APP_ACTION_NAME) VALUES('CONFIRM_REGISTRATION');
INSERT INTO DBO.APP_ACTION(APP_ACTION_NAME) VALUES('UNLOCK_APP_USER');
INSERT INTO DBO.APP_ACTION(APP_ACTION_NAME) VALUES('FORGOT_PASSWORD');